# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/godi_rec.ui'
#
# Created: Fri May 23 17:57:15 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GodiRec(object):
    def setupUi(self, GodiRec):
        GodiRec.setObjectName(_fromUtf8("GodiRec"))
        GodiRec.resize(331, 470)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("cinema3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GodiRec.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(GodiRec)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 311, 173))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ButtonPlay = QtGui.QPushButton(self.verticalLayoutWidget)
        self.ButtonPlay.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("media23.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonPlay.setIcon(icon1)
        self.ButtonPlay.setCheckable(False)
        self.ButtonPlay.setObjectName(_fromUtf8("ButtonPlay"))
        self.horizontalLayout.addWidget(self.ButtonPlay)
        self.ButtonStop = QtGui.QPushButton(self.verticalLayoutWidget)
        self.ButtonStop.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("media26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonStop.setIcon(icon2)
        self.ButtonStop.setObjectName(_fromUtf8("ButtonStop"))
        self.horizontalLayout.addWidget(self.ButtonStop)
        self.ButtonRec = QtGui.QPushButton(self.verticalLayoutWidget)
        self.ButtonRec.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("record6.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonRec.setIcon(icon3)
        self.ButtonRec.setObjectName(_fromUtf8("ButtonRec"))
        self.horizontalLayout.addWidget(self.ButtonRec)
        self.ButtonCut = QtGui.QPushButton(self.verticalLayoutWidget)
        self.ButtonCut.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("cutting.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonCut.setIcon(icon4)
        self.ButtonCut.setObjectName(_fromUtf8("ButtonCut"))
        self.horizontalLayout.addWidget(self.ButtonCut)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.LabelTime = QtGui.QLabel(self.verticalLayoutWidget)
        self.LabelTime.setObjectName(_fromUtf8("LabelTime"))
        self.horizontalLayout_2.addWidget(self.LabelTime)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.LabelProjekt = QtGui.QLabel(self.verticalLayoutWidget)
        self.LabelProjekt.setObjectName(_fromUtf8("LabelProjekt"))
        self.horizontalLayout_2.addWidget(self.LabelProjekt)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.ButtonSave = QtGui.QPushButton(self.verticalLayoutWidget)
        self.ButtonSave.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("1400625665_sync.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonSave.setIcon(icon5)
        self.ButtonSave.setObjectName(_fromUtf8("ButtonSave"))
        self.horizontalLayout_2.addWidget(self.ButtonSave)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.ListTracks = QtGui.QListView(self.verticalLayoutWidget)
        self.ListTracks.setObjectName(_fromUtf8("ListTracks"))
        self.verticalLayout.addWidget(self.ListTracks)
        self.formLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 190, 311, 231))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_titel = QtGui.QLabel(self.formLayoutWidget)
        self.label_titel.setObjectName(_fromUtf8("label_titel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_titel)
        self.LineEditTitle = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditTitle.setObjectName(_fromUtf8("LineEditTitle"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LineEditTitle)
        self.label_artist = QtGui.QLabel(self.formLayoutWidget)
        self.label_artist.setObjectName(_fromUtf8("label_artist"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_artist)
        self.LineEditArtist = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditArtist.setObjectName(_fromUtf8("LineEditArtist"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.LineEditArtist)
        self.label_album = QtGui.QLabel(self.formLayoutWidget)
        self.label_album.setObjectName(_fromUtf8("label_album"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_album)
        self.LineEditAlbum = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditAlbum.setObjectName(_fromUtf8("LineEditAlbum"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.LineEditAlbum)
        self.label_genre = QtGui.QLabel(self.formLayoutWidget)
        self.label_genre.setObjectName(_fromUtf8("label_genre"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_genre)
        self.LineEditGenre = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditGenre.setObjectName(_fromUtf8("LineEditGenre"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.LineEditGenre)
        self.label_kommentar = QtGui.QLabel(self.formLayoutWidget)
        self.label_kommentar.setObjectName(_fromUtf8("label_kommentar"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_kommentar)
        self.LineEditComment = QtGui.QLineEdit(self.formLayoutWidget)
        self.LineEditComment.setReadOnly(True)
        self.LineEditComment.setObjectName(_fromUtf8("LineEditComment"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.LineEditComment)
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label)
        self.LineEditDate = QtGui.QDateEdit(self.formLayoutWidget)
        self.LineEditDate.setLocale(QtCore.QLocale(QtCore.QLocale.German, QtCore.QLocale.Germany))
        self.LineEditDate.setMinimumDate(QtCore.QDate(2014, 1, 1))
        self.LineEditDate.setObjectName(_fromUtf8("LineEditDate"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.LineEditDate)
        self.ButtonChange = QtGui.QPushButton(self.formLayoutWidget)
        self.ButtonChange.setObjectName(_fromUtf8("ButtonChange"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.ButtonChange)
        GodiRec.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(GodiRec)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuGodiRec = QtGui.QMenu(self.menubar)
        self.menuGodiRec.setObjectName(_fromUtf8("menuGodiRec"))
        GodiRec.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(GodiRec)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        GodiRec.setStatusBar(self.statusbar)
        self.ActionExit = QtGui.QAction(GodiRec)
        self.ActionExit.setObjectName(_fromUtf8("ActionExit"))
        self.ActionNewProject = QtGui.QAction(GodiRec)
        self.ActionNewProject.setObjectName(_fromUtf8("ActionNewProject"))
        self.ActionOpenProject = QtGui.QAction(GodiRec)
        self.ActionOpenProject.setObjectName(_fromUtf8("ActionOpenProject"))
        self.menuGodiRec.addAction(self.ActionNewProject)
        self.menuGodiRec.addAction(self.ActionOpenProject)
        self.menuGodiRec.addAction(self.ActionExit)
        self.menubar.addAction(self.menuGodiRec.menuAction())

        self.retranslateUi(GodiRec)
        QtCore.QMetaObject.connectSlotsByName(GodiRec)

    def retranslateUi(self, GodiRec):
        GodiRec.setWindowTitle(_translate("GodiRec", "GodiRec", None))
        self.ButtonCut.setToolTip(_translate("GodiRec", "<html><head/><body><p>beginnt einen neuen Track.</p></body></html>", None))
        self.LabelTime.setText(_translate("GodiRec", "-- / --", None))
        self.LabelProjekt.setText(_translate("GodiRec", "erzeuge Projekt", None))
        self.ButtonSave.setToolTip(_translate("GodiRec", "<html><head/><body><p>Aktuallisiert die Track liste</p></body></html>", None))
        self.label_titel.setText(_translate("GodiRec", "Titel:", None))
        self.label_artist.setText(_translate("GodiRec", "Artist:", None))
        self.label_album.setText(_translate("GodiRec", "Album:", None))
        self.label_genre.setText(_translate("GodiRec", "Genre:", None))
        self.label_kommentar.setText(_translate("GodiRec", "Kommentar:", None))
        self.label.setText(_translate("GodiRec", "Jahr:", None))
        self.LineEditDate.setDisplayFormat(_translate("GodiRec", "yyyy", None))
        self.ButtonChange.setToolTip(_translate("GodiRec", "<html><head/><body><p>speichert aktuelle Taggs ab</p></body></html>", None))
        self.ButtonChange.setText(_translate("GodiRec", "Change", None))
        self.menuGodiRec.setTitle(_translate("GodiRec", "File", None))
        self.ActionExit.setText(_translate("GodiRec", "Exit", None))
        self.ActionExit.setShortcut(_translate("GodiRec", "Ctrl+Q", None))
        self.ActionNewProject.setText(_translate("GodiRec", "Neues Projekt", None))
        self.ActionNewProject.setShortcut(_translate("GodiRec", "Ctrl+N", None))
        self.ActionOpenProject.setText(_translate("GodiRec", "Altes Projekt", None))
        self.ActionOpenProject.setShortcut(_translate("GodiRec", "Ctrl+O", None))

